/* DuoFit private coaching layer. Loaded before the legacy app script. */
(function(){
'use strict';
const cfg=window.FATLOSS_CONFIG||{};
const BASE=String(cfg.SUPABASE_URL||'').replace(/\/$/,'');
const KEY=String(cfg.SUPABASE_KEY||'');
const AUTH_KEY='duofit.auth.v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const monday=d=>{const x=new Date(d.getFullYear(),d.getMonth(),d.getDate());x.setDate(x.getDate()-((x.getDay()+6)%7));return todayFrom(x);};
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
const recoveryHash=async code=>{const clean=String(code||'').replace(/[^a-fA-F0-9]/g,'').toLowerCase();if(!/^[a-f0-9]{32}$/.test(clean))throw new Error('恢复码格式不正确，请输入完整的 32 位字符。');const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(clean));return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');};
const pick=(arr,v,exclusive=[])=>exclusive.includes(v)?(arr.includes(v)?[]:[v]):(arr.includes(v)?arr.filter(x=>x!==v):[...arr.filter(x=>!exclusive.includes(x)),v]);
class DuoCoach {
  constructor(hooks){this.h=hooks;this.session=null;this.member=null;this.profile=null;this.weeks={};this.partnerActivity={};this.partnerTrend=[];this.current=null;this.step=0;this.draft=this.blank();this.note='';this.aiText='';this.chat=[[],[],[]];this.chatInput='';this.weekHealth=[];this.weekNote='';this.weekShown=false;this.busy=false;this.root=null;this.pushSupported=('serviceWorker' in navigator && 'PushManager' in window && 'Notification' in window);}
  blank(){return {version:1,goals:[],focus:[],age:'',height:'',weight:'',target:'',health:[],healthDetail:'',frequency:'',duration:'',equipment:[],diet:'',notes:['','',''],confirmedAt:null};}
  get active(){return !!this.member&&!this.provisional;}
  get person(){return this.member?.person||null;}
  get peer(){return this.person==='hus'?'wife':'hus';}
  headers(auth=true){const h={'Content-Type':'application/json','apikey':KEY};if(auth&&this.session?.access_token)h.Authorization='Bearer '+this.session.access_token;return h;}
  async request(path,body,auth=true){const r=await fetch(BASE+path,{method:'POST',headers:this.headers(auth),body:JSON.stringify(body)});const raw=await r.text();let data;try{data=raw?JSON.parse(raw):null;}catch{data={message:raw};}if(!r.ok){const e=new Error(data?.message||data?.error||data?.msg||'请求失败 '+r.status);e.status=r.status;throw e;}return data;}
  async authRequest(path,body){const r=await fetch(BASE+path,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){const raw=d.msg||d.message||d.error_description||d.error||'登录失败';const e=new Error(/anonymous sign-ins are disabled|anonymous_provider_disabled/i.test(raw)?'云端尚未开启免邮箱进入，暂时无法保存档案。请在 Supabase Auth 中开启匿名登录。':raw);e.status=r.status;throw e;}return d;}
  saveSession(d){this.session=d;localStorage.setItem(AUTH_KEY,JSON.stringify(d));}
  async refresh(){if(!this.session?.refresh_token)return false;if(this.session.expires_at&&this.session.expires_at>Date.now()/1000+90)return true;try{const d=await this.authRequest('/auth/v1/token?grant_type=refresh_token',{refresh_token:this.session.refresh_token});this.saveSession(d);return true;}catch{this.session=null;localStorage.removeItem(AUTH_KEY);return false;}}
  async rpc(name,args={}){if(!await this.refresh())throw new Error('登录已过期，请重新登录。');return this.request('/rest/v1/rpc/'+name,args);}
  mount(){this.root=document.createElement('div');this.root.id='duoCoach';this.root.hidden=true;document.body.appendChild(this.root);this.root.addEventListener('click',e=>this.click(e));this.root.addEventListener('input',e=>this.input(e));this.root.addEventListener('keydown',e=>{if(e.target.matches('[data-profile-note]')&&e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();this.root.querySelector('[data-coach="interpret"]')?.click();}});document.addEventListener('click',e=>{if(!this.root.contains(e.target)&&e.target.closest('[data-coach]'))this.click(e);});}
  async start(){this.mount();let saved;try{saved=JSON.parse(localStorage.getItem(AUTH_KEY)||'null');}catch{}this.session=saved;if(this.session){if(await this.refresh()){try{const r=await this.rpc('fl_private_pull',{p_since:new Date(Date.now()-120*864e5).toISOString().slice(0,10)});this.member=r.member;await this.load(r);return;}catch(e){if(!String(e.message).includes('pairing_required'))this.h.entryError?.('连接失败，请检查网络后重试。');}}else this.h.entryError?.('本机身份无法验证，可用个人恢复码找回。');}
    else try{await this.signInAnonymous();}catch(e){this.h.entryError?.(/尚未开启免邮箱进入/.test(e.message)?'云端尚未开启免邮箱进入；现在仍可先填写 4 步，保存前需开启。':'暂时无法建立本机身份，请检查网络。');}
    if(!this.member)this.h.needsRole?.();}
  async signInAnonymous(){const d=await this.authRequest('/auth/v1/signup',{data:{}});if(!d?.access_token||!d?.user?.id)throw new Error('没有获得本机身份，请检查匿名登录配置。');this.saveSession(d);return d;}
  async pair(family,person,showRecovery=true){const m=await this.rpc('fl_claim_role',{p_family:family,p_person:person});this.member=m;const r=await this.rpc('fl_private_pull',{p_since:new Date(Date.now()-120*864e5).toISOString().slice(0,10)});this.provisional=false;await this.load(r);if(showRecovery)try{await this.issueRecoveryCode();this.renderRecovery();}catch(e){this.notice('档案已建立，但恢复码生成失败：'+e.message);}}
  beginRole(person,family){if(!['hus','wife'].includes(person))throw new Error('请先选择角色。');const code=String(family||this.h.family()||'').trim()||Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>(x%36).toString(36)).join('');if(!/^[A-Za-z0-9]{8,40}$/.test(code))throw new Error('家庭口令需要 8–40 位字母或数字。');this.member={person,family:code};this.provisional=true;this.profile=null;this.draft=this.legacyDraft(this.h.initialMeasures?.(person)||{});this.step=0;this.previewPlan=null;this.chat=[[],[],[]];this.chatInput='';this.renderOnboard();}
  async ensurePaired(){if(!this.provisional)return;if(this.ready)await this.ready;if(!this.session)await this.signInAnonymous();const draft=this.draft,plan=this.previewPlan,chat=this.chat;await this.pair(this.member.family,this.member.person,false);this.draft=draft;this.previewPlan=plan;this.chat=chat;this.step=3;this.provisional=false;this.renderOnboard();}
  async issueRecoveryCode(){const bytes=crypto.getRandomValues(new Uint8Array(16));const raw=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');await this.rpc('fl_recovery_set',{p_hash:await recoveryHash(raw)});this.recoveryCode=raw.toUpperCase().match(/.{1,4}/g).join('-');}
  async recover(code){if(!this.session)await this.signInAnonymous();const m=await this.rpc('fl_recover_role',{p_hash:await recoveryHash(code)});this.member=m;const r=await this.rpc('fl_private_pull',{p_since:new Date(Date.now()-120*864e5).toISOString().slice(0,10)});await this.load(r);try{await this.issueRecoveryCode();this.renderRecovery();}catch(e){this.notice('档案已恢复，但新恢复码生成失败：'+e.message);}}
  renderRecovery(){this.current='recovery';this.shell(`<div class="coach-top"><div><b>保存个人恢复码</b><small>只属于你，不要发给伴侣</small></div></div><article class="coach-card"><p>换手机或清除浏览器数据时，用它找回私人档案。新码生成后旧码失效；请保存到你自己的安全位置。</p><div class="coach-recovery-code">${esc(this.recoveryCode||'')}</div><button data-coach="recovery-copy">复制恢复码</button><button class="coach-secondary" data-coach="recovery-saved">我已保存，继续</button></article>`);}
  renderRecoverEntry(msg=''){this.current='recover-entry';this.shell(`<div class="coach-top"><button data-coach="gate">‹</button><div><b>找回私人档案</b><small>输入仅你持有的恢复码</small></div></div><article class="coach-card"><p>恢复后，这台设备会成为你的新设备；原设备将不能再同步此档案。</p><label>个人恢复码<input data-coach-field="recovery" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="8 组 4 位字符"></label>${msg?`<p class="coach-alert">${esc(msg)}</p>`:''}<button data-coach="recover-submit">恢复我的档案</button></article>`);}
  async load(r){this.member=r.member;this.profile=r.profile||null;if(this.profile?.confirmedAt)this.draft={...this.blank(),...this.profile};this.weeks={};(r.weeks||[]).forEach(w=>this.weeks[w.weekStart]=w.body);this.partnerActivity={};(r.partnerActivity||[]).forEach(a=>this.partnerActivity[a.date]=!!a.checked);this.partnerTrend=(r.partnerTrend||[]).sort((a,b)=>a.date.localeCompare(b.date));this.h.setIdentity(this.member.person,this.member.family,this.session.user?.id||this.session.user_id);
    const checkins={},measures={};(r.checkins||[]).forEach(x=>checkins[this.person+'_'+x.date]=x.body);(r.measures||[]).forEach(x=>measures[this.person+'_'+x.date]=x.body);this.h.setStore({checkins,measures});this.root.hidden=true;this.h.render();if(!this.profile?.confirmedAt){this.draft=this.legacyDraft(measures);this.step=0;this.previewPlan=null;this.renderOnboard();}else this.checkWeekly();}
  legacyDraft(measures){const d=this.blank(),history=Object.values(measures).sort((a,b)=>a.date.localeCompare(b.date));const g=history.filter(m=>m.goal).at(-1)?.goal;if(g){d.age=g.age||'';d.height=g.height||'';d.weight=g.start||'';d.target=g.target!==g.start?g.target:'';d.goals=d.target?['减脂']:['建立运动习惯'];}const latest=history.filter(m=>typeof m.weight==='number').at(-1);if(latest)d.weight=latest.weight;return d;}
  editProfile(){this.draft={...this.blank(),...this.profile,notes:[...(this.profile?.notes||['','',''])]};this.chat=[[],[],[]];this.chatInput='';this.previewPlan=null;this.step=0;this.renderOnboard();}
  async sync(store,dirty){if(!this.active||this.busy)return;this.busy=true;try{for(const key of [...dirty]){const kind=key[0],id=key.slice(2),b=kind==='c'?store.checkins[id]:store.measures[id];if(!b||b.person!==this.person)continue;await this.rpc(kind==='c'?'fl_private_put_checkin':'fl_private_put_measure',{p_date:b.date,p_body:b});this.h.clearDirty(key);}
      const r=await this.rpc('fl_private_pull',{p_since:new Date(Date.now()-120*864e5).toISOString().slice(0,10)});this.profile=r.profile||this.profile;this.weeks={};(r.weeks||[]).forEach(w=>this.weeks[w.weekStart]=w.body);this.partnerActivity={};(r.partnerActivity||[]).forEach(a=>this.partnerActivity[a.date]=!!a.checked);this.partnerTrend=(r.partnerTrend||[]).sort((a,b)=>a.date.localeCompare(b.date));const checkins={},measures={};(r.checkins||[]).forEach(x=>checkins[this.person+'_'+x.date]=x.body);(r.measures||[]).forEach(x=>measures[this.person+'_'+x.date]=x.body);this.h.setStore({checkins,measures});this.h.setSync('ok');this.h.render();
    }catch(e){if(String(e.message).includes('pairing_required')){this.member=null;this.profile=null;this.h.clearIdentity?.();this.renderRecoverEntry('这个档案已在另一台设备恢复。');}else this.h.setSync('error');console.warn('private sync',e);}finally{this.busy=false;}}
  partnerChecked(date){return this.partnerActivity[date]===true;}
  ownWeek(date=today()){return this.weeks[monday(new Date(date+'T12:00:00'))]||null;}
  schedule(date,base){const c=this.h.getCheckin(date);if(date===today()&&c.dailyChoice==='rest')return {kind:'rest'};const w=this.ownWeek(date);const key=w?.plan?.days?.[date]||(monday(new Date(date+'T12:00:00'))===monday(new Date())?this.carryPlan().days[date]:null);if(key)return key==='REST'?{kind:'rest'}:{kind:'train',w:key};return base;}
  mealSwap(meal){return String((this.ownWeek()?.plan||this.carryPlan()).mealSwaps?.[meal]||'').slice(0,100);}
  carryPlan(){const current=this.proposedPlan(),previous=this.weeks[monday(new Date(Date.now()-7*864e5))]?.plan;if(!previous?.days)return current;const old=Object.keys(previous.days).sort(),now=Object.keys(current.days).sort();return {...previous,days:Object.fromEntries(now.map((date,i)=>[date,['A','B','W','N','REST'].includes(previous.days[old[i]])?previous.days[old[i]]:'REST']))};}
  goalTitle(){const p=this.profile;return p?.goals?.length?p.goals.join('、'):(p?.notes?.[0]||'尚未设定目标');}
  dailyCard(){const c=this.h.getCheckin(today());const choice=c.dailyChoice;return `<section class="coach-mini"><div class="coach-mini-head"><img src="assets/avatar-${this.person}.png" alt=""><div><b>今天的状态，告诉我一下</b><small>我会决定照常、短版或休息</small></div></div>${choice?`<p>今天选择：${choice==='short'?'短版训练':choice==='rest'?'休息':'照常执行'}</p>`:''}<button type="button" data-coach="daily">${choice?'重新调整今天':'和伙伴聊聊今天'}</button></section>`;}
  weeklyCard(){const status=this.ownWeek()?.bodyStatus||this.profile?.health||[];return `<section class="coach-mini"><div class="coach-mini-head"><img src="assets/avatar-${this.person}.png" alt=""><div><b>这周的目标</b><small>${esc(this.goalTitle())}${this.profile?.target?` · 期待 ${esc(this.profile.target)} kg`:''}</small><small>身体状态：${esc(status.join('、')||'待确认')}</small></div></div><button data-coach="weekly">查看或调整本周计划</button></section>`;}
  pushCard(){return `<section class="coach-mini"><b>每周计划提醒</b><p>${!this.pushSupported?'此设备暂不支持系统推送，打开 App 时仍会提醒。':!cfg.PUSH_PUBLIC_KEY?'推送服务尚未配置，打开 App 时仍会提醒。':'开启后，即使关闭 App 也可收到每周提醒。'}</p>${this.pushSupported&&cfg.PUSH_PUBLIC_KEY?'<button type="button" data-coach="push">开启系统通知</button>':''}</section>`;}
  partnerCard(){const points=this.partnerTrend.slice(-12);const chart=points.length>1?this.chart(points):'<p>伴侣还没有足够的体重记录</p>';return `<section class="coach-mini"><b>伴侣今天${this.partnerChecked(today())?'已打卡':'还没有打卡'}</b><small>只分享打卡状态与相对体重变化</small>${chart}</section>`;}
  chart(points){const vals=points.map(p=>Number(p.changeKg)),lo=Math.min(...vals)-.2,hi=Math.max(...vals)+.2;const xy=vals.map((v,i)=>[10+i*280/(vals.length-1),82-(v-lo)/(hi-lo)*65]);return `<svg viewBox="0 0 300 95" role="img" aria-label="伴侣体重相对变化曲线"><polyline fill="none" stroke="var(--me)" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" points="${xy.map(p=>p.map(x=>x.toFixed(1)).join(',')).join(' ')}"/></svg><small>相对首次记录的变化，不显示原始体重</small>`;}
  shell(body,view=''){this.root.hidden=false;this.root.dataset.person=this.person||'';this.root.innerHTML=`<div class="coach-screen${view?' coach-screen-'+view:''}"><div class="coach-panel">${body}</div></div>`;}
  renderSignoutConfirm(){this.current='signout-confirm';this.shell(`<article class="coach-card"><h2>清除这台设备的登录？</h2><p>请先保存个人恢复码。清除登录后，家庭口令无法找回你的私人档案。</p><button class="coach-secondary" data-coach="close">返回档案</button><button data-coach="signout-confirm">确认清除本机登录</button></article>`);}
  q(label,desc,content){return `<div class="coach-question"><b>${label}</b><p>${desc}</p>${content}</div>`;}
  chips(group,values,selected){return `<div class="coach-chips">${values.map(v=>`<button data-coach-group="${group}" data-value="${esc(v)}" aria-pressed="${selected.includes(v)}">${esc(v)}</button>`).join('')}</div>`;}
  field(name,label,value,placeholder='',type='text'){return `<label class="coach-field">${label}<input data-profile-field="${name}" value="${esc(value)}" placeholder="${placeholder}" type="${type}"></label>`;}
  renderOnboard(msg=''){this.current='onboard';const d=this.draft,stage=this.step;const mascot=`<div class="coach-bubble"><img src="assets/avatar-${this.person}.png" alt=""><div><b>你的健康伙伴</b><p>${['先聊聊你想要的变化。','最近的身体情况，也请告诉我。','计划要适合你的日常。','我把你说的整理成首周草案。'][stage]}</p></div></div>`;
    let body='';if(stage===0)body=this.q('想实现什么目标？','可多选',this.chips('goals',['减脂','塑形','建立运动习惯'],d.goals))+this.q('想改善的地方','可多选',this.chips('focus',['腰腹','臀腿','背肩','全身'],d.focus))+`<div class="coach-grid">${this.field('age','年龄 *',d.age,'28','number')}${this.field('height','身高 cm *',d.height,'165','number')}${this.field('weight','当前体重 kg *',d.weight,'60','number')}${this.field('target','期待体重 kg',d.target,'塑形可不填','number')}</div>`;
    if(stage===1)body=this.q('最近身体有什么需要留意？','可多选；“暂时没有”与其他项互斥',this.chips('health',['经期不适','最近生病','身体疼痛','有慢性病','疲惫或睡眠差','暂时没有','暂不想说'],d.health))+(d.health.some(x=>!['暂时没有','暂不想说'].includes(x))?this.field('healthDetail','补充影响计划的情况',d.healthDetail,'例如：深蹲时右膝疼'):'');
    if(stage===2)body=this.q('一周方便练几次？','选一个',this.chips('frequency',['每周 2 次','每周 3 次','每周 4 次','时间不固定'],[d.frequency]))+this.q('每次大概多久？','选一个',this.chips('duration',['10 分钟','20 分钟','30 分钟','看当天状态'],[d.duration]))+this.q('手边有什么器械？','可多选',this.chips('equipment',['无器械','瑜伽垫','哑铃'],d.equipment))+this.field('diet','饮食限制或偏好',d.diet,'例如：不吃奶制品，晚餐常外食');
    if(stage===3){const plan=this.previewPlan||this.proposedPlan();body=`<div class="coach-summary"><b>目标</b><p>${esc(d.goals.join('、')||d.notes[0]||'待确认')} · ${esc(d.focus.join('、')||'全身')}</p><b>基础信息</b><p>${esc(d.age)} 岁 · ${esc(d.height)} cm · 当前 ${esc(d.weight)} kg${d.target?` · 期待 ${esc(d.target)} kg`:''}</p><b>身体情况</b><p>${esc(d.health.join('、')||d.notes[1]||'暂未说明')} ${esc(d.healthDetail)}</p><b>训练安排</b><p>${esc(d.frequency||'时间不固定')}，${esc(d.duration||'看当天状态')}；${esc(d.equipment.join('、')||'无器械')}</p><b>饮食偏好</b><p>${esc(d.diet||'无特别限制')}</p><b>首周训练草案</b><p>${esc(Object.entries(plan.days).filter(([,v])=>v!=='REST').map(([k,v])=>k.slice(5)+' '+v).join(' · ')||'本周先休息，恢复后再调整')}</p><b>这周饮食调整</b><p>${esc(Object.values(plan.mealSwaps||{}).filter(Boolean).join('；')||'暂未生成个性餐食；如有饮食禁忌，请不要照搬默认菜品。')}</p><small>饮食热量沿用现有安全计算；AI 负责组合和解释，启用前仍需你确认。</small></div>`;if(this.aiError)body+=`<p class="coach-alert">${esc(this.aiError)} 这份训练草案先按你确认的选项保守安排。</p>`;}
    const understood=stage<3?`<div class="coach-understood"><b>✦ 我听懂的是</b><p>${esc(this.chat[stage].at(-1)?.reply||'先点选一项，或者在下方直接告诉我。')}</p></div>`:'';
    const composer=stage<3?`<div class="coach-composer">${msg?`<p class="coach-compose-error" role="alert">${esc(msg)}</p>`:''}<div class="coach-compose-field"><textarea data-profile-note rows="1" placeholder="或者直接跟我说…" aria-label="直接告诉健康伙伴">${esc(this.chatInput)}</textarea><button type="button" data-coach="interpret" aria-label="发送给健康伙伴" title="发送">↑</button></div><small>点选后不会自动保存，你确认再继续</small></div>`:'';
    this.shell(`<div class="coach-onboard"><div class="coach-onboard-scroll"><div class="coach-top"><button data-coach="back" aria-label="返回">‹</button><div><b>我的健康伙伴</b><small>正在了解你 · 第 ${stage+1} / 4 步</small></div><span class="coach-online${this.aiError?' off':''}">${this.aiError?'AI 暂不可用':this.aiReady?'● 在线':'● 待连接'}</span></div><div class="coach-progress">${[0,1,2,3].map(i=>`<i class="${i<=stage?'on':''}"></i>`).join('')}</div><article class="coach-card">${mascot}${body}${understood}${stage===3&&msg?`<p class="coach-alert">${esc(msg)}</p>`:''}<button data-coach="next">${['确认目标，继续','确认身体情况，继续','确认日常安排，继续','确认并启用计划'][stage]}</button><small class="coach-fine">请核对这张卡片里的信息，再进入下一步</small></article><small class="coach-private">你确认后才会保存；健康信息不会分享给伴侣。</small></div>${composer}</div>`,'onboard');}
  proposedPlan(){const d=this.draft,mon=monday(new Date()),unwell=d.health.some(x=>['经期不适','最近生病','身体疼痛','疲惫或睡眠差'].includes(x))||/疼|痛|伤|病|经期|月经|疲惫|睡眠差|没睡/.test((d.notes?.[1]||'')+' '+(d.healthDetail||'')),n=unwell?0:parseInt(String(d.frequency).match(/\d/)?.[0]||'2',10),offsets=n>=4?[0,1,3,5]:n===3?[0,2,4]:n===2?[0,3]:[],days={};for(let i=0;i<7;i++){const dt=new Date(mon+'T12:00:00');dt.setDate(dt.getDate()+i);days[todayFrom(dt)]='REST';}offsets.forEach((off,i)=>{const dt=new Date(mon+'T12:00:00');dt.setDate(dt.getDate()+off);days[todayFrom(dt)]=this.person==='hus'?(d.equipment.includes('哑铃')?(i%2?'B':'A'):'N'):'W';});return {days,frequency:d.frequency,duration:d.duration,dietNote:d.diet,reason:unwell?'当前有身体不适，本周先安排休息；身体恢复后再调整。':'按你的时间和身体情况安排，确认后可每天调整。'};}
  safePlan(suggestion,base,status=[]){const allowed=this.person==='hus'?(this.draft.equipment.includes('哑铃')?['A','B','N']:['N']):['W','N'];const max=Math.min(4,Math.max(0,parseInt(String(this.draft.frequency).match(/\d/)?.[0]||'2',10)));const oldNarrative=status===this.draft.health&&/疼|痛|伤|病|经期|月经|疲惫|睡眠差|没睡/.test((this.draft.notes?.[1]||'')+' '+(this.draft.healthDetail||''));const unwell=status.some(x=>['经期不适','最近生病','身体疼痛','慢性病情况变化','疲惫或睡眠差'].includes(x))||oldNarrative;let count=0;const days={};for(const date of Object.keys(base.days).sort()){const key=suggestion?.days?.[date]||base.days[date];days[date]=!unwell&&allowed.includes(key)&&count<max?key:'REST';if(days[date]!=='REST')count++;}return {...base,...suggestion,days};}
  async coachAI(mode,text,extra={}){try{if(this.ready)await this.ready;if(!this.session)await this.signInAnonymous();const out=await this.request('/functions/v1/coach'+(cfg.AI_REGION?'?forceFunctionRegion='+encodeURIComponent(cfg.AI_REGION):''),{mode,text,person:this.person,profile:this.draft,extra});this.aiError='';this.aiReady=true;return out;}catch(e){this.aiReady=false;const detail=String(e.message||'');this.aiError=/匿名登录|anonymous sign-ins/i.test(detail)?'当前云端未开启免邮箱进入，AI 暂时不能识别。':e.status===404?'AI 聊天服务尚未部署，暂时不能识别。':e.status===403&&/pairing_required/.test(detail)?'AI 聊天服务需要更新，建档前的对话暂时不可用。':typeof location!=='undefined'&&location.protocol==='file:'?'当前是本地文件预览，AI 对话需在已部署的网站上测试。':e.status===503?'AI 服务尚未配置完成。':'AI 暂时无法连接，请稍后再试。';console.warn('coach AI fallback',e);return null;}}
  async confirmStep(){const d=this.draft,s=this.step;if(s<3&&this.chatInput.trim()){d.notes[s]=(d.notes[s]+' '+this.chatInput.trim()).trim().slice(0,500);this.chatInput='';}if(s===0){if(!d.goals.length&&!d.notes[0])return this.renderOnboard('先选目标，或用自己的话描述。');if(!(Number(d.age)>=18&&Number(d.age)<=80&&Number(d.height)>=130&&Number(d.height)<=210&&Number(d.weight)>=30&&Number(d.weight)<=200))return this.renderOnboard('请检查年龄、身高和当前体重。');if(d.target&&(Number(d.target)<30||Number(d.target)>200||Number(d.target)<18.5*(Number(d.height)/100)**2))return this.renderOnboard('期待体重过低，请调整或留空。');}
    if(s===1&&!d.health.length&&!d.notes[1])return this.renderOnboard('请选择身体情况，或选“暂不想说”。');if(s===2&&(!d.frequency||!d.duration)&&!d.notes[2])return this.renderOnboard('请选训练频率和时长，或描述你的安排。');if(s<3){this.step++;this.aiText='';if(this.step===3){this.previewPlan=this.proposedPlan();const suggestion=await this.coachAI('plan','根据确认的档案生成首周计划');if(suggestion?.plan?.days)this.previewPlan=this.safePlan(suggestion.plan,this.previewPlan,d.health);}this.renderOnboard();return;}
    const profile={...d,confirmedAt:new Date().toISOString(),notes:d.notes.map(x=>String(x).slice(0,500))};const plan=this.previewPlan||this.proposedPlan();
    await this.ensurePaired();await this.rpc('fl_private_put_profile',{p_body:profile});const weekStart=monday(new Date());await this.rpc('fl_private_put_week',{p_week_start:weekStart,p_body:{plan,bodyStatus:d.health,reviewedAt:new Date().toISOString()}});this.profile=profile;this.weeks[weekStart]={plan,bodyStatus:d.health,reviewedAt:new Date().toISOString()};this.h.saveLegacyGoal(profile);this.h.render();try{await this.issueRecoveryCode();this.renderRecovery();}catch(e){this.notice('计划已保存，但恢复码生成失败：'+e.message);}}
  checkWeekly(){if(!this.profile?.confirmedAt)return;const week=monday(new Date()),key='duofit.week.prompt.'+(this.session.user?.id||this.person)+'.'+week;if(this.weeks[week]?.reviewedAt||localStorage.getItem(key))return;this.weekHealth=[];this.weekNote='';this.weekProposed=null;this.weekKey=key;this.renderWeekly();}
  renderWeekly(msg=''){this.current='weekly';const old=this.weeks[monday(new Date(Date.now()-7*864e5))]?.bodyStatus||this.profile.health||[];this.shell(`<div class="coach-top"><button data-coach="close">×</button><div><b>新的一周</b><small>计划要调整吗？</small></div></div><article class="coach-card"><div class="coach-bubble"><img src="assets/avatar-${this.person}.png" alt=""><div><b>你的健康伙伴</b><p>先确认这周的身体状态，再决定要不要改计划。</p></div></div><div class="coach-summary"><b>你设定的目标</b><p>${esc(this.goalTitle())} · 想改善 ${esc(this.profile.focus?.join('、')||'全身')}${this.profile.target?` · 期待 ${esc(this.profile.target)} kg`:''}</p><b>上次身体记录</b><p>${esc(old.join('、')||'暂无记录')}</p></div>${this.q('这周身体状态如何？','可多选',this.chips('weekHealth',['目前无特别不适','经期不适','最近生病','身体疼痛','疲惫或睡眠差','慢性病情况变化'],this.weekHealth))}<textarea data-week-note placeholder="可补充：这周膝盖不舒服、时间变少了…">${esc(this.weekNote)}</textarea>${this.weekProposed?`<div class="coach-summary"><b>建议的新安排</b><p>${esc(Object.entries(this.weekProposed.days||{}).filter(([,v])=>v!=='REST').map(([k,v])=>k.slice(5)+' '+v).join(' · ')||'本周以休息为主')}</p><b>饮食建议</b><p>${esc(Object.values(this.weekProposed.mealSwaps||{}).filter(Boolean).join('；')||'沿用现有饮食份量')}</p></div>`:''}${msg?`<p class="coach-alert">${esc(msg)}</p>`:''}<button data-coach="week-adjust">${this.weekProposed?'确认使用这个计划':'需要调整，和伙伴聊聊'}</button><button class="coach-secondary" data-coach="week-keep">沿用现有计划</button></article>`);}
  async weeklyDecision(adjust){if(!this.weekHealth.length&&!this.weekNote.trim())return this.renderWeekly('先确认这周的身体状态。');const risk=this.weekHealth.some(x=>['经期不适','最近生病','身体疼痛','慢性病情况变化','疲惫或睡眠差'].includes(x))||/疼|痛|伤|病|不适|疲惫|睡眠差|没睡/.test(this.weekNote);if(!adjust&&risk)return this.renderWeekly('这周身体状态有变化，先看看更合适的安排。');const weekStart=monday(new Date()),base=this.ownWeek()||{},plan=base.plan||this.carryPlan();let newPlan=plan;if(adjust&&!this.weekProposed){const ai=await this.coachAI('weekly',this.weekNote||this.weekHealth.join('、'),{weekStart});if(ai?.plan?.days)newPlan=this.safePlan(ai.plan,plan,this.weekHealth);else if(risk)newPlan={...plan,days:Object.fromEntries(Object.keys(plan.days||{}).map(k=>[k,'REST'])),reason:'身体状态有变化，先以休息和轻量活动为主；恢复后再调整。'};}if(risk)newPlan={...newPlan,days:Object.fromEntries(Object.keys(newPlan.days||{}).map(k=>[k,'REST']))};if(adjust&&!this.weekProposed){this.weekProposed=newPlan;this.renderWeekly();return;}if(adjust)newPlan=this.weekProposed;
    const body={plan:newPlan,bodyStatus:[...this.weekHealth],bodyNote:this.weekNote.slice(0,500),reviewedAt:new Date().toISOString()};await this.rpc('fl_private_put_week',{p_week_start:weekStart,p_body:body});this.weeks[weekStart]=body;if(this.weekKey)localStorage.setItem(this.weekKey,'1');this.root.hidden=true;this.current=null;this.h.render();}
  renderDaily(msg=''){this.current='daily';this.shell(`<div class="coach-top"><button data-coach="close">×</button><div><b>今天怎么安排</b><small>只调整今天，不改整周</small></div></div><article class="coach-card"><div class="coach-bubble"><img src="assets/avatar-${this.person}.png" alt=""><div><b>你的健康伙伴</b><p>今天身体和时间怎么样？</p></div></div>${this.q('身体状态','选最接近的一项',this.chips('dailyState',['状态不错','经期不适','生病或恢复中','身体疼痛','很疲惫'],[this.dailyState]))}${this.q('今天可用时间','选一项',this.chips('dailyTime',['按原计划','只有 10 分钟','今天没时间'],[this.dailyTime]))}${msg?`<p class="coach-alert">${esc(msg)}</p>`:''}<button data-coach="daily-save">给我今天的建议</button></article>`);}
  async saveDaily(){if(!this.dailyState||!this.dailyTime)return this.renderDaily('先告诉我身体状态和可用时间。');let choice=this.dailyState==='状态不错'?(this.dailyTime==='按原计划'?'original':this.dailyTime==='只有 10 分钟'?'short':'rest'):'rest';const ai=await this.coachAI('daily',this.dailyState+'；'+this.dailyTime,{date:today()});if(['original','short','rest'].includes(ai?.choice))choice=ai.choice;if(this.dailyState!=='状态不错')choice='rest';const c={...this.h.getCheckin(today()),person:this.person,date:today(),dailyState:this.dailyState,dailyTime:this.dailyTime,dailyChoice:choice};this.h.putCheckin(c);this.root.hidden=true;this.current=null;this.h.render();}
  async subscribePush(){if(!this.pushSupported)return this.notice('当前设备不支持系统通知。');const pub=String(cfg.PUSH_PUBLIC_KEY||'');if(!pub)return this.notice('推送服务尚未配置，站内提醒仍然可用。');try{const perm=await Notification.requestPermission();if(perm!=='granted')return this.notice('你没有开启通知，站内提醒仍然可用。');const reg=await navigator.serviceWorker.ready;const bytes=Uint8Array.from(atob(pub.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});const j=sub.toJSON();await this.rpc('fl_push_save',{p_endpoint:j.endpoint,p_p256dh:j.keys.p256dh,p_auth:j.keys.auth});this.notice('已开启每周系统提醒。');}catch(e){this.notice('开启失败：'+e.message);}}
  notice(text){if(this.current==='onboard')this.renderOnboard(text);else if(this.current==='weekly')this.renderWeekly(text);else if(this.current==='daily')this.renderDaily(text);else if(this.current==='recover-entry')this.renderRecoverEntry(text);else{this.root.hidden=false;this.shell(`<article class="coach-card"><p>${esc(text)}</p><button data-coach="close">知道了</button></article>`);}}
  async click(e){const b=e.target.closest('button');if(!b)return;const a=b.dataset.coach;if(b.dataset.coachGroup){const g=b.dataset.coachGroup,v=b.dataset.value;if(g==='weekHealth'){this.weekProposed=null;this.weekHealth=pick(this.weekHealth,v,['目前无特别不适']);this.renderWeekly();return;}if(g==='dailyState'||g==='dailyTime'){this[g]=v;this.renderDaily();return;}if(['goals','focus','health','equipment'].includes(g)){const exclusive=g==='health'?['暂时没有','暂不想说']:g==='focus'?['全身']:g==='equipment'?['无器械']:[];this.draft[g]=exclusive.includes(v)?(this.draft[g].includes(v)?[]:[v]):pick(this.draft[g],v,exclusive);this.renderOnboard();return;}this.draft[g]=v;this.renderOnboard();return;}
    try{if(a==='gate'){this.root.hidden=true;this.current=null;this.h.showRoleChoice?.();}
      else if(a==='recover-open'){this.h.hideEntry?.();this.recoveryInput='';this.renderRecoverEntry();}
      else if(a==='recover-submit'){if(this.ready)await this.ready;const code=this.root.querySelector('[data-coach-field="recovery"]')?.value||this.recoveryInput;await this.recover(code);}
      else if(a==='recovery-copy'){await navigator.clipboard.writeText(this.recoveryCode);this.renderRecovery();}
      else if(a==='recovery-saved'){this.recoveryCode=null;this.root.hidden=true;this.current=null;if(!this.profile?.confirmedAt)this.renderOnboard();else this.checkWeekly();}
      else if(a==='show-recovery'){await this.issueRecoveryCode();this.renderRecovery();}
      else if(a==='copy-family'){await navigator.clipboard.writeText(this.member.family);this.notice('已复制配对口令，请通过可信方式发给伴侣。');}
      else if(a==='signout'){this.renderSignoutConfirm();}
      else if(a==='signout-confirm'){try{await this.request('/auth/v1/logout',{});}catch(_){}this.session=null;this.member=null;this.profile=null;this.weeks={};this.partnerActivity={};this.partnerTrend=[];localStorage.removeItem(AUTH_KEY);this.h.clearIdentity?.();this.root.hidden=true;this.current=null;this.h.needsRole?.();}
      else if(a==='next'){await this.confirmStep();}
      else if(a==='back'){if(this.current==='onboard'&&this.step>0){this.step--;this.previewPlan=null;this.renderOnboard();}else if(this.current==='onboard'&&this.provisional){this.member=null;this.provisional=false;this.root.hidden=true;this.current=null;this.h.showRoleChoice?.();}else this.root.hidden=true;}
      else if(a==='interpret'){if(this.aiSending)return;const text=this.chatInput.trim();if(!text)return this.renderOnboard('先写一句你的情况。');this.aiSending=true;b.disabled=true;try{const x=await this.coachAI('interpret',text,{step:this.step,history:this.chat[this.step].slice(-4)});if(!x)return this.renderOnboard(this.aiError||'AI 暂时无法连接，文字已保留，可以稍后重试。');this.chat[this.step].push({user:text,reply:x.summary||'我已记录，请核对卡片。'});this.draft.notes[this.step]=(this.draft.notes[this.step]+' '+text).trim().slice(0,500);this.chatInput='';if(x.suggestions)this.applySuggestions(x.suggestions);this.renderOnboard();}finally{this.aiSending=false;b.disabled=false;}}
      else if(a==='close'){if(this.current==='weekly'&&this.weekKey)localStorage.setItem(this.weekKey,'1');this.root.hidden=true;this.current=null;}
      else if(a==='daily'){const c=this.h.getCheckin(today());this.dailyState=c.dailyState||'';this.dailyTime=c.dailyTime||'';this.renderDaily();}else if(a==='daily-save'){await this.saveDaily();}
      else if(a==='weekly'){this.weekHealth=[];this.weekNote='';this.weekProposed=null;this.renderWeekly();}
      else if(a==='week-adjust'){await this.weeklyDecision(true);}else if(a==='week-keep'){await this.weeklyDecision(false);}
      else if(a==='push'){await this.subscribePush();}
    }catch(err){this.notice(err.message||'操作失败，请稍后重试。');}}
  applySuggestions(s){const allowed={goals:['减脂','塑形','建立运动习惯'],focus:['腰腹','臀腿','背肩','全身'],health:['经期不适','最近生病','身体疼痛','有慢性病','疲惫或睡眠差','暂时没有','暂不想说'],equipment:['无器械','瑜伽垫','哑铃']};for(const [k,options] of Object.entries(allowed)){if(Array.isArray(s[k])&&s[k].length)this.draft[k]=s[k].filter(x=>options.includes(x));}if(['每周 2 次','每周 3 次','每周 4 次','时间不固定'].includes(s.frequency))this.draft.frequency=s.frequency;if(['10 分钟','20 分钟','30 分钟','看当天状态'].includes(s.duration))this.draft.duration=s.duration;if(s.diet)this.draft.diet=String(s.diet).slice(0,250);}
  input(e){const f=e.target.dataset.profileField;if(f)this.draft[f]=e.target.value;if(e.target.dataset.profileNote!==undefined)this.chatInput=e.target.value;if(e.target.dataset.weekNote!==undefined){this.weekNote=e.target.value;this.weekProposed=null;}if(e.target.dataset.coachField==='recovery')this.recoveryInput=e.target.value;}
}
function todayFrom(d){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');}
window.DuoCoach=DuoCoach;
})();
