const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');assert(fs.readFileSync(path.join(root,'sw.js'),'utf8').includes('notificationclick'),'push click handler');
assert(html.indexOf('<script src="config.js"></script>') < html.indexOf('<script src="private-coach.js?v=37"></script>'), 'config loads before coaching');
const inline = html.slice(html.lastIndexOf('<script>') + 8, html.lastIndexOf('</script>'));
const memory = new Map();
const elements = new Map();
const element = key => {
  if (!elements.has(key)) {const classes=new Set();elements.set(key, {innerHTML: '', textContent: '', value: '', hidden: false, dataset:{}, classList: {add(...xs){xs.forEach(x=>classes.add(x))}, remove(...xs){xs.forEach(x=>classes.delete(x))}, contains(x){return classes.has(x)}}, addEventListener(){}, setAttribute(){}, querySelector(){return null}});}
  return elements.get(key);
};
const sandbox = {
  window: {FATLOSS_CONFIG: {}}, localStorage: {getItem:k=>memory.get(k) ?? null,setItem:(k,v)=>memory.set(k,String(v)),removeItem:k=>memory.delete(k)},
  document: {querySelector:element,querySelectorAll:()=>[],getElementById:element,body:{style:{}},addEventListener(){},activeElement:{blur(){}}},
  location: {hash:'',pathname:'/',search:'',protocol:'file:'}, history:{replaceState(){}}, navigator:{},
  setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame:f=>f(), matchMedia:()=>({matches:true}), console, Date, AbortController, URL,
};
const exported = ['calcPlan','menuFor','dayRange','scheduleFor','dayDone','viewToday','viewDiet','dietWeekCard','viewTrain','viewRecord','renderRecordData','privateTrendCard','goalCard','roundsFor','ymd','MEALS','goalOf','getCheckin','planFor','buildSteps','drawRun','feedRows','openPicker','showRoleChoice','extraMoveRows','extraDone','toggleExtraMove','EXTRA_MOVES','refreshCalendarDay','ackDirty','markDirty','activityInfo','activityStreak','coupleStreakCard','checkinHistoryCard','dietDayRows'];
const code = inline.replace('/* ---------- boot ---------- */', `globalThis.__app = {${exported.join(',')},getDirty:()=>dirty,setDietSelectedDate:v=>{dietSelectedDate=v},setHistorySelectedDate:v=>{historySelectedDate=v},setHistoryPerson:v=>{historyPerson=v}, setStore:v=>{store=v},setMe:v=>{me=v;viewP=v},setViewP:v=>{viewP=v},setDietWeekOffset:v=>{dietWeekOffset=v},setCoach:v=>{privateCoach=v},setTab:v=>{tab=v},setRunState:v=>{runState=v}};return;`);
vm.runInNewContext(code, sandbox, {filename:'index-inline.js'});
const app = sandbox.__app;
app.openPicker(false);assert(element('#pick').classList.contains('open'),'original animation picker opens');assert.equal(element('#lm').dataset.phase,'choose','reduced motion lands on role choice');
const date = app.ymd(new Date());
const goal = (start,target) => ({height:170,age:32,start,target,pace:'gentle',adj:0,level:0,cardio:false,at:date});
const meals = Object.fromEntries([...app.MEALS].map(m=>[m,'plan']));
app.setMe('hus');
const pendingCheckin={person:'hus',date,meals:{breakfast:'plan'}},pendingKey='c:hus_'+date;
app.setStore({checkins:{['hus_'+date]:pendingCheckin},measures:{}});app.markDirty(pendingKey);
const sentCheckin=JSON.stringify(pendingCheckin);pendingCheckin.meals.lunch='over';
assert.equal(app.ackDirty(pendingKey,sentCheckin),false,'old upload cannot acknowledge a newer local checkin');assert(app.getDirty().includes(pendingKey));
assert.equal(app.ackDirty(pendingKey,JSON.stringify(pendingCheckin)),true);assert(!app.getDirty().includes(pendingKey),'matching upload clears the pending record');
app.setStore({checkins:{['hus_'+date]:{person:'hus',date,meals,workout:'done'},['wife_'+date]:{person:'wife',date,meals,workout:'done'}},measures:{['hus_'+date]:{person:'hus',date,weight:78,goal:goal(78,72)},['wife_'+date]:{person:'wife',date,weight:47.3,goal:goal(47.3,46),waist:63}}});
assert(app.planFor('hus').kcal >= 1500, 'historical kcal floor');
assert(app.dayRange('hus')[0] > 0, 'historical menu calculates');
assert(app.menuFor('hus').breakfast.items.length > 0, 'historical menu preserved');assert(app.dayDone('hus',new Date()),'historical full day checkin');assert.equal(app.buildSteps('A').at(-1).type,'end','historical workout flow');
app.viewToday(); assert(element('#view').innerHTML.includes('今天两个人的进度'), 'historical partner progress');
app.viewTrain(); assert(element('#view').innerHTML.includes('这周我的安排'), 'weekly view stays available');assert(!element('#view').innerHTML.includes('A、B 每周交替'),'training no longer asks for A/B choice');
app.viewDiet(); assert(element('#view').innerHTML.includes('看谁的计划'), 'historical diet switch');assert(element('#view').innerHTML.includes('饮食打卡记录'),'diet page shows weekly checkin history');
assert(app.dietWeekCard('hus').includes(`${date} 早餐：按计划`),'current week reads the saved meal status');
const oldDate=app.ymd(new Date(new Date().setDate(new Date().getDate()-7)));
app.setStore({checkins:{['hus_'+date]:{person:'hus',date,meals,workout:'done'},['wife_'+date]:{person:'wife',date,meals,workout:'done'},['hus_'+oldDate]:{person:'hus',date:oldDate,meals:{breakfast:'over',lunch:'skip'}},['wife_'+oldDate]:{person:'wife',date:oldDate,meals:{breakfast:'plan'}}},measures:{['hus_'+date]:{person:'hus',date,weight:78,goal:goal(78,72)},['wife_'+date]:{person:'wife',date,weight:47.3,goal:goal(47.3,46),waist:63}}});
const oldWeek=app.dietWeekCard('hus',-1);assert(oldWeek.includes(`${oldDate} 早餐：吃多了`)&&oldWeek.includes(`${oldDate} 午餐：没吃`),'previous week keeps distinct meal results');assert(!oldWeek.includes(`${oldDate} 早餐：按计划`),'weekly history only reads the selected person');
assert(app.dietWeekCard('hus').includes('data-diet-week="-1" aria-label="上一周"'),'past week remains browsable');
app.viewRecord();app.renderRecordData();assert(element('#recPair').innerHTML.includes('47.3'), 'historical record view');
const coach = {active:true,person:'hus',profile:{goals:['减脂'],focus:['腰腹']},goalTitle(){return '减脂'},partnerChecked(){return true},partnerCard(){return '<div>relative only</div>'},dailyCard(){return '<div>daily coach</div>'},weeklyCard(){return '<div>weekly coach</div>'},pushCard(){return '<div>push coach</div>'},mealSwap(){return '鸡蛋和蔬菜'},schedule(_,base){return base}};
app.setCoach(coach);
app.viewToday();assert(element('#view').innerHTML.includes('伴侣今天已打卡'));assert(!element('#view').innerHTML.includes('今天两个人的进度'));assert(!element('#view').innerHTML.includes('47.3'));
coach.profile.diet='不吃奶制品';app.viewToday();assert(!element('#view').innerHTML.includes('脱脂牛奶'),'restricted diet hides default foods');app.setViewP('wife');app.setDietWeekOffset(-1);app.viewDiet();assert(!element('#view').innerHTML.includes('看谁的计划'));assert(!element('#view').innerHTML.includes('47.3'));assert(element('#view').innerHTML.includes('鸡蛋和蔬菜'));assert(!element('#view').innerHTML.includes('晚餐轮换'),'restricted diet hides generic dinner rotation');assert(element('#view').innerHTML.includes(`${oldDate} 早餐：吃多了`)&&!element('#view').innerHTML.includes(`${oldDate} 早餐：按计划`),'private diet history only shows the signed-in person');app.setDietWeekOffset(0);
assert(element('#view').innerHTML.includes('class="mplan-suggestion"'),'personal meal suggestion is present');
app.setViewP('wife');app.viewTrain();assert(!element('#view').innerHTML.includes('这周两个人的安排'));assert(!element('#view').innerHTML.includes('老婆 · 居家臀腿'));
app.setViewP('hus');app.viewRecord();app.renderRecordData();assert(!element('#recPair').innerHTML.includes('47.3'));assert(element('#recPair').innerHTML.includes('relative only'));assert(!element('#recData').innerHTML.includes('47.3'));assert(app.privateTrendCard().includes('<circle')&&app.privateTrendCard().includes('再记录一次即可形成趋势'),'one measurement is visible on private trend');assert(element('#view').innerHTML.includes('<details class="private-settings">'),'private actions are collapsed under settings');
coach.schedule=()=>({kind:'train',w:'A'});app.viewTrain();assert(element('#view').innerHTML.includes('assets/moves/a-goblet-squat.gif'),'today workout shows animated exercise');assert(!element('#view').innerHTML.includes('assets/moves/b-floor-press.gif'),'tomorrow workout is not offered as a second choice');
coach.schedule=()=>({kind:'rest'});assert.equal(app.scheduleFor('hus',new Date()).kind,'rest','daily rest override');app.viewTrain();assert(element('#view').innerHTML.includes('搜索动作')&&element('#view').innerHTML.includes('data-extra-move="d-seated-glute-squeeze"'),'rest day offers suggested activity and search');
coach.profile.health=['身体疼痛'];app.viewTrain();assert(element('#view').innerHTML.includes('今天以休息为主')&&!element('#view').innerHTML.includes('data-extra-move="d-seated-glute-squeeze"'),'recovery rest does not recommend exercise');coach.profile.health=[];
coach.profile.health=['身体疼痛'];coach.ownWeek=()=>({bodyStatus:['目前无特别不适'],bodyNote:''});app.viewTrain();assert(element('#view').innerHTML.includes('data-extra-move="d-seated-glute-squeeze"'),'current weekly status supersedes old pain');coach.profile.health=[];
assert(app.extraMoveRows({extraMoves:[]},'臀桥').includes('臀桥'),'exercise search finds matching movements');
const extraCheckin=app.toggleExtraMove({person:'hus',date,meals:{},workout:null},'warm-march');assert.deepEqual([...app.extraDone(extraCheckin)],['warm-march'],'optional move is logged separately');assert.equal(extraCheckin.workout,null,'optional move does not silently complete scheduled workout');assert.equal(app.extraDone(app.toggleExtraMove(extraCheckin,'warm-march')).length,0,'optional move can be undone');
assert(app.EXTRA_MOVES.every(m=>fs.existsSync(path.join(root,'assets/moves',m.img+'.gif'))),'all movement animations exist');
const bodyweightSteps=app.buildSteps('N');app.setRunState({key:'N',steps:bodyweightSteps,i:bodyweightSteps.length-1});app.drawRun();assert(element('#runBody').innerHTML.includes('data-run="finish"'),'bodyweight workout can be completed and saved');
const walkSteps=app.buildSteps('C');app.setRunState({key:'C',steps:walkSteps,i:walkSteps.length-1});app.drawRun();assert(element('#runBody').innerHTML.includes('data-run="finish"'),'scheduled walk can be completed and saved');
// Count saved check-in days, rather than requiring every meal or exercise to be complete.
const dayAgo=n=>app.ymd(new Date(new Date().getFullYear(),new Date().getMonth(),new Date().getDate()-n));
app.setCoach(null);app.setMe('hus');app.setStore({checkins:{['hus_'+dayAgo(1)]:{person:'hus',date:dayAgo(1),meals:{breakfast:'plan'}},['hus_'+dayAgo(2)]:{person:'hus',date:dayAgo(2),meals:{lunch:'over'}},['hus_'+dayAgo(4)]:{person:'hus',date:dayAgo(4),meals:{breakfast:'skip'}}},measures:{}});
assert.equal(app.activityStreak(app.activityInfo('hus').checked).count,2,'today has a grace period; partial and over meals both count');
app.setStore({checkins:{['hus_'+dayAgo(2)]:{person:'hus',date:dayAgo(2),meals:{breakfast:'plan'}}},measures:{}});
assert.equal(app.activityStreak(app.activityInfo('hus').checked).count,0,'a missing yesterday really breaks the current chain');
assert.equal(app.activityStreak(d=>d<=dayAgo(0)).count,120,'streak calculations are bounded');
const historyCoach={...coach,partnerActivitySince:dayAgo(119),partnerActivityUntil:dayAgo(0),partnerChecked:d=>[dayAgo(1),dayAgo(2)].includes(d)};
app.setCoach(historyCoach);assert.equal(app.activityStreak(app.activityInfo('wife').checked).count,2,'partner historical booleans support streaks');
assert(app.coupleStreakCard().includes('连续记录'),'private record page includes both partner streaks');
historyCoach.partnerActivityUntil=dayAgo(3);assert.equal(app.activityInfo('wife').ready,false,'stale partner data is unknown rather than zero');
delete historyCoach.partnerActivitySince;assert(app.coupleStreakCard().includes('历史状态待同步'),'older servers do not pretend missing history means no check-ins');
app.setStore({checkins:{['hus_'+dayAgo(1)]:{person:'hus',date:dayAgo(1),meals:{breakfast:'skip'},food:{breakfast:{items:[{n:'旧食物',q:'',k:999}],kcal:999}}},['wife_'+dayAgo(1)]:{person:'wife',date:dayAgo(1),food:{breakfast:{items:[{n:'PRIVATE_PEER_FOOD'}],kcal:444}}}},measures:{}});
app.setHistorySelectedDate(dayAgo(1));const historyHtml=app.checkinHistoryCard();assert(!historyHtml.includes('PRIVATE_PEER_FOOD'),'partner meal details never enter shared history');
app.setHistoryPerson('wife');historyCoach.partnerRecordSharing='off';
assert(app.checkinHistoryCard().includes('已关闭打卡详情共享'),'unshared partner details have an explanation');assert(!app.checkinHistoryCard().includes('PRIVATE_PEER_FOOD'),'a tab cannot expose legacy partner rows');
historyCoach.partnerRecordSharing='on';historyCoach.partnerCheckin=d=>d===dayAgo(1)?{person:'wife',date:d,meals:{breakfast:'plan'},food:{breakfast:{items:[{n:'共享酸奶',q:'1 杯',k:120}],kcal:120}},workout:'done',stand:2}:null;
const sharedHistory=app.checkinHistoryCard();assert(sharedHistory.includes('共享酸奶')&&sharedHistory.includes('120')&&sharedHistory.includes('已完成'),'opted-in peer meal and activity details are rendered');assert(!sharedHistory.includes('data-meal=')&&!sharedHistory.includes('data-food='),'peer records are read-only');assert(!sharedHistory.includes('PRIVATE_PEER_FOOD'),'shared results come only from the scoped RPC');
historyCoach.partnerRecordSharing='unknown';assert(app.checkinHistoryCard().includes('联网后重新连接'),'unavailable shared records are not mislabelled empty');
app.setHistoryPerson('hus');
assert(!app.dietDayRows('hus',dayAgo(1)).includes('999'),'a skipped meal does not display stale food calories');
assert(!app.dietDayRows('hus',dayAgo(1),true).includes('data-meal='),'past days are read-only and cannot accidentally change today');
console.log('PASS saved-day streaks, today grace, real gaps, history bounds, unknown peer data and private food isolation');
console.log('PASS historical plan, menu, partner views; PASS private today, diet, train, record, schedule');

// Run the actual coaching class with mocked IO for the new state transitions.
const classSandbox = {window:{FATLOSS_CONFIG:{}},navigator:{clipboard:{writeText:async()=>{}}},localStorage:sandbox.localStorage,document:{},console:{warn(){}},Date,setTimeout,clearTimeout,AbortController,crypto:require('node:crypto').webcrypto,TextEncoder};
vm.runInNewContext(fs.readFileSync(path.join(root,'private-coach.js'),'utf8'),classSandbox,{filename:'private-coach.js'});
const DuoCoach = classSandbox.window.DuoCoach;
let latest = {person:'hus',date};
const c = new DuoCoach({getCheckin:()=>latest,putCheckin:v=>{latest=v},render(){},saveLegacyGoal(){},setIdentity(){},setStore(){},family:()=>''});
c.member={person:'hus',family:'abcdefgh'};c.root={hidden:false,innerHTML:'',dataset:{}};c.draft={...c.blank(),age:'32',height:'170',weight:'78',goals:['减脂'],focus:['腰腹'],health:['身体疼痛'],frequency:'每周 3 次',duration:'20 分钟',diet:'不吃奶制品'};
assert(Object.values(c.proposedPlan().days).every(x=>x==='REST'),'painful week rests');assert.equal(Object.keys(c.proposedPlan().days)[0],date,'first plan starts on confirmation day');assert.equal(c.legacyDraft({['hus_'+date]:{person:'hus',date,weight:77}}).weight,77,'existing weight prefilled');c.draft.health=['暂时没有'];assert(Object.values(c.proposedPlan().days).includes('N'),'no dumbbells selects bodyweight workout');c.draft.notes[1]='最近膝盖疼';assert(Object.values(c.proposedPlan().days).every(x=>x==='REST'),'free text pain blocks exercise');c.draft.notes[1]='';c.draft.health=['身体疼痛'];
c.profile={...c.draft,confirmedAt:new Date().toISOString()};c.dailyState='身体疼痛';c.dailyTime='按原计划';c.coachAI=async()=>{throw new Error('daily choices must not wait for AI')};
(async()=>{
  await c.saveDaily();assert.equal(latest.dailyChoice,'rest','AI cannot override pain');assert.equal(c.schedule(date,{kind:'train',w:'A'}).kind,'rest');
  c.dailyState='状态不错';c.dailyTime='只有 10 分钟';await c.saveDaily();assert.equal(latest.dailyChoice,'short');
  classSandbox.fetch=(_,options)=>new Promise((_,reject)=>options.signal.addEventListener('abort',()=>reject(new Error('aborted'))));
  const slowRequest=new DuoCoach({});await assert.rejects(slowRequest.request('/functions/v1/coach',{},true,5),/ai_timeout/,'AI request has a client-side deadline');
  c.draft.health=['暂时没有'];c.step=2;c.draft.frequency='每周 3 次';c.draft.duration='20 分钟';
  const basePlan=c.proposedPlan();const dates=Object.keys(basePlan.days);let aiCalls=0;
  c.coachAI=async mode=>{aiCalls++;return mode==='plan'?{summary:'建议',plan:{days:Object.fromEntries(dates.map((d,i)=>[d,i===0?'A':'REST'])),mealSwaps:{breakfast:'鸡蛋和水果'}}}:{plan:{days:Object.fromEntries(dates.map(d=>[d,'A']))}}};
  const calls=[];c.rpc=async(name,args)=>{calls.push({name,args})};
  await c.confirmStep();assert.equal(c.step,3);assert(!Object.values(c.previewPlan.days).includes('A'),'incompatible AI equipment is rejected');assert(c.root.innerHTML.includes('鸡蛋和水果'),'fourth card previews AI diet');assert(c.root.innerHTML.includes('健康伙伴的判断')&&c.root.innerHTML.includes('建议'),'fourth card displays AI plan analysis');assert.equal(calls.length,0,'no save before confirmation');
  const pendingPlan=new DuoCoach({family:()=>''});pendingPlan.member={person:'hus'};pendingPlan.root={hidden:false,innerHTML:'',dataset:{}};pendingPlan.draft={...c.draft};pendingPlan.step=3;pendingPlan.previewPlan=pendingPlan.proposedPlan();let finishPlan;pendingPlan.coachAI=()=>new Promise(resolve=>{finishPlan=resolve});
  const planning=pendingPlan.generatePlan();assert(pendingPlan.root.innerHTML.includes('正在生成个性化计划')&&pendingPlan.root.innerHTML.includes('data-coach="next" disabled'),'plan generation has visible pending state');finishPlan(null);await planning;
  pendingPlan.draft.notes=['想改善久坐后的肩背僵硬','最近睡眠不太好','晚餐常在外面吃'];pendingPlan.chat[0].push({user:'想改善久坐后的肩背僵硬',reply:'会考虑肩背和久坐的情况'});pendingPlan.previewPlan.reason='结合久坐和可用时间安排';pendingPlan.renderOnboard();assert(pendingPlan.root.innerHTML.includes('想改善久坐后的肩背僵硬')&&pendingPlan.root.innerHTML.includes('会考虑肩背和久坐的情况'),'fourth card shows original AI input and interpretation');assert(pendingPlan.root.innerHTML.includes('结合久坐和可用时间安排')&&pendingPlan.root.innerHTML.includes('coach-goal-text'),'fourth card shows plan reasoning and prominent goal');
  pendingPlan.aiError='AI 回复格式不完整，请重新生成。';pendingPlan.aiErrorContext=3;pendingPlan.renderOnboard();assert(pendingPlan.root.innerHTML.includes('data-coach="retry-plan"'),'failed plan can be retried');pendingPlan.step=2;pendingPlan.renderOnboard();assert(!pendingPlan.root.innerHTML.includes('AI 建议未生成'),'error from step four does not persist on another card');
  await c.confirmStep();assert(calls.some(x=>x.name==='fl_private_put_profile'));assert(calls.some(x=>x.name==='fl_private_put_week'&&x.args.p_body.plan.mealSwaps.breakfast==='鸡蛋和水果'));
  c.weekHealth=['身体疼痛'];c.weekNote='膝盖疼';c.weekProposed=null;const count=calls.length;
  await c.weeklyDecision(true);assert.equal(calls.length,count,'weekly proposal requires second confirmation');assert(Object.values(c.weekProposed.days).every(v=>v==='REST'),'weekly pain guard');
  const afterPreview=aiCalls;await c.weeklyDecision(true);assert.equal(aiCalls,afterPreview,'confirmed weekly preview reused');assert(calls.some(x=>x.name==='fl_private_put_week'&&x.args.p_body.bodyStatus.includes('身体疼痛')));
  const pulled = {member:{family:'abcdefgh',person:'hus'},profile:{...c.profile,confirmedAt:new Date().toISOString()},weeks:[{weekStart:Object.keys(c.weeks)[0],body:Object.values(c.weeks)[0]}],checkins:[{date,body:{person:'hus',date,meals:{}}}],measures:[{date,body:{person:'hus',date,weight:78}}],partnerActivity:[{date,checked:true}],partnerTrend:[{date,changeKg:-1.2}]};
  let received=null, pushed=[];const peerSafe = new DuoCoach({setIdentity(){},setStore:v=>{received=v},render(){},clearDirty(){},setSync(){},getCheckin:()=>({}),family:()=>''});
  peerSafe.root={hidden:false,innerHTML:'',dataset:{}};peerSafe.session={user:{id:'u1'}};peerSafe.rpc=async name=>{pushed.push(name);return pulled};
  await peerSafe.load(pulled);assert(received.measures['hus_'+date]);assert(!received.measures['wife_'+date]);assert.equal(peerSafe.partnerTrend[0].changeKg,-1.2);
  assert(memory.has('duofit.profile.v1.u1'),'confirmed profile is saved for an offline return');
  await peerSafe.sync({checkins:{['hus_'+date]:{person:'hus',date}},measures:{['wife_'+date]:{person:'wife',date,weight:47.3}}},['c:hus_'+date,'m:wife_'+date]);
  assert(pushed.includes('fl_private_put_checkin'));assert(!pushed.includes('fl_private_put_measure'),'partner dirty data never uploads');
  assert(html.includes('data-lm-role="hus"')&&html.includes('data-lm-role="wife"'),'original role picker retained');assert(html.includes('id="entryFamily"')&&html.includes('data-coach="recover-open"'),'pairing and recovery stay secondary on role picker');
  memory.delete('duofit.auth.v1');memory.delete('duofit.paired.v1');let needsRole=0,returnedToRoles=0;const guest=new DuoCoach({family:()=>'',needsRole:()=>{needsRole++},showRoleChoice:()=>{returnedToRoles++},setIdentity(){},setStore(){},render(){},getCheckin:()=>({}),saveLegacyGoal(){}});guest.mount=()=>{guest.root={hidden:true,innerHTML:'',dataset:{}}};guest.authRequest=async path=>{assert.equal(path,'/auth/v1/signup');return {access_token:'anon',refresh_token:'refresh',user:{id:'anon-1',is_anonymous:true}}};
  await guest.start();assert.equal(needsRole,1,'first entry opens original role picker');assert(guest.root.hidden,'no login method overlay on first entry');
  const newPull={member:{person:'wife',family:'abcdefgh'},profile:null,weeks:[],checkins:[],measures:[],partnerActivity:[],partnerTrend:[]},entryCalls=[];
  guest.rpc=async(name,args)=>{entryCalls.push({name,args});if(name==='fl_claim_role')return newPull.member;if(name==='fl_private_pull')return newPull;return null};
  guest.beginRole('wife','abcdefgh');assert.equal(entryCalls.length,0,'role selection does not wait for backend');assert.equal(guest.current,'onboard');assert.equal(guest.step,0);assert(guest.root.innerHTML.includes('第 1 / 4 步'),'role selection goes directly to four-step profile');assert(!guest.recoveryCode,'recovery prompt waits until after plan');assert(!guest.root.innerHTML.includes('邮箱'));
  assert.equal(guest.root.dataset.person,'wife','wife onboarding uses wife theme');assert(guest.root.innerHTML.includes('coach-composer')&&guest.root.innerHTML.includes('href="#ic-send"'),'bottom composer uses the shared SVG send icon');assert(!guest.root.innerHTML.includes('>发送给健康伙伴</button>'),'no second full-width send button');
  assert(guest.root.innerHTML.includes('title="发送" disabled'),'empty composer cannot send');
  const sendControl={disabled:true};guest.root.querySelector=()=>sendControl;
  guest.input({target:{dataset:{profileNote:''},value:'准备开始运动'}});assert(!sendControl.disabled,'typing enables send without rerendering the textarea');
  guest.input({target:{dataset:{profileNote:''},value:'  '}});assert(sendControl.disabled,'whitespace alone does not enable send');
  guest.chatInput='最近膝盖疼';let finishAnalysis;guest.coachAI=()=>new Promise(resolve=>{finishAnalysis=()=>{guest.aiError='AI 聊天服务尚未部署';resolve(null)}});
  const sending=guest.click({target:{closest:()=>({dataset:{coach:'interpret'},disabled:false})}});
  assert(guest.root.innerHTML.includes('正在分析中')&&guest.root.innerHTML.includes('coach-spinner'),'AI send shows analysis state');
  assert(guest.root.innerHTML.includes('data-coach="interpret" aria-label="正在分析中" title="正在分析中" disabled'),'AI send disabled while pending');
  finishAnalysis();await sending;assert.equal(guest.chatInput,'最近膝盖疼','failed AI send keeps draft text');assert(guest.root.innerHTML.includes('AI 聊天服务尚未部署'),'specific AI error shown');assert(!guest.root.innerHTML.includes('coach-spinner'),'analysis state clears after failure');guest.chatInput='';
  guest.chatInput='想练背部';guest.coachAI=async()=>({partial:true});await guest.click({target:{closest:()=>({dataset:{coach:'interpret'},disabled:false})}});assert.equal(guest.chatInput,'想练背部','invalid AI output preserves typed description');assert(guest.root.innerHTML.includes('没有自动提取选项'),'invalid AI output gives a usable fallback');guest.chatInput='';
  await guest.click({target:{closest:()=>({dataset:{coach:'back'}})}});assert.equal(returnedToRoles,1,'first card back returns to role choice');guest.beginRole('wife','abcdefgh');
  Object.assign(guest.draft,{goals:['减脂'],focus:['腰腹'],age:'32',height:'170',weight:'70',health:['暂时没有'],frequency:'每周 2 次',duration:'20 分钟'});guest.coachAI=async()=>null;
  await guest.confirmStep();await guest.confirmStep();await guest.confirmStep();assert.equal(guest.step,3);assert.equal(entryCalls.length,0,'four profile cards stay available before pairing');
  await guest.confirmStep();assert(entryCalls.some(x=>x.name==='fl_claim_role'&&x.args.p_person==='wife'));assert(entryCalls.some(x=>x.name==='fl_private_put_profile'));assert.equal(guest.current,'recovery','personal recovery follows confirmed plan');
  let returningNeedsRole=0;const returning=new DuoCoach({family:()=>'',needsRole:()=>{returningNeedsRole++},setIdentity(){},setStore(){},render(){},getCheckin:()=>({})});returning.mount=()=>{returning.root={hidden:true,innerHTML:'',dataset:{}}};returning.refresh=async()=>true;returning.rpc=async()=>pulled;returning.checkWeekly=()=>{};
  await returning.start();assert(returning.active,'saved account returns to private app');assert.equal(returningNeedsRole,0,'returning account skips role selection');
  memory.set('duofit.auth.v1',JSON.stringify({access_token:'cached',refresh_token:'cached',user:{id:'u1'}}));
  let offlineIdentity=null,offlineSync=null,offlineRenders=0;
  const offlineReturn=new DuoCoach({setIdentity:(person,family,uid)=>{offlineIdentity={person,family,uid}},setSync:v=>{offlineSync=v},render:()=>{offlineRenders++},getCheckin:()=>({})});
  offlineReturn.mount=()=>{offlineReturn.root={hidden:true,innerHTML:'',dataset:{}}};offlineReturn.refresh=async()=>true;offlineReturn.rpc=async()=>{throw new Error('network unavailable')};
  assert.equal(await offlineReturn.start(),'home','cached confirmed profile opens despite a failed cloud pull');
  assert(offlineReturn.active&&offlineReturn.profile.confirmedAt,'offline return keeps the confirmed profile');
  assert.equal(offlineIdentity.uid,'u1','offline cache is scoped to the authenticated user');
  assert.equal(offlineSync,'offline');assert.equal(offlineRenders,1);
  offlineReturn.rpc=async()=>pulled;offlineReturn.h.setStore=()=>{};offlineReturn.h.clearDirty=()=>{};
  await offlineReturn.sync({checkins:{},measures:{}},[]);assert.equal(offlineSync,'ok','background sync reconnects after offline entry');
  const denied=new DuoCoach({setIdentity(){throw Error('denied cache must not load')},render(){}});
  denied.mount=()=>{denied.root={hidden:true,innerHTML:'',dataset:{}}};denied.refresh=async()=>true;
  denied.rpc=async()=>{const e=new Error('permission denied');e.status=403;throw e};
  assert.equal(await denied.start(),'error','explicit permission failure does not use an offline profile');
  memory.set('duofit.auth.v1',JSON.stringify({access_token:'uncached',refresh_token:'uncached',user:{id:'u-uncached'}}));
  let mistakenRolePrompts=0;
  const interrupted=new DuoCoach({needsRole:()=>{mistakenRolePrompts++},setIdentity(){},setStore(){},render(){},getCheckin:()=>({})});interrupted.mount=()=>{interrupted.root={hidden:true,innerHTML:'',dataset:{}}};interrupted.refresh=async()=>true;interrupted.rpc=async()=>{throw new Error('network unavailable')};
  assert.equal(await interrupted.start(),'error','failed profile pull has a distinct startup state');
  assert.equal(interrupted.current,'startup-error','existing account sees retry and recovery');
  assert(interrupted.root.innerHTML.includes('重新连接')&&interrupted.root.innerHTML.includes('个人恢复码'));
  assert.equal(mistakenRolePrompts,0,'temporary pull failure never restarts onboarding');
  assert(memory.has('duofit.auth.v1'),'temporary pull failure keeps the saved identity');
  interrupted.rpc=async()=>pulled;interrupted.checkWeekly=()=>{};
  assert.equal(await interrupted.restoreSession(),'home','retry restores the saved profile');
  assert.equal(interrupted.profile.confirmedAt,pulled.profile.confirmedAt);
  assert(memory.has('duofit.paired.v1'),'paired account is remembered separately from the auth token');
  memory.delete('duofit.auth.v1');
  const missingToken=new DuoCoach({needsRole:()=>{mistakenRolePrompts++}});missingToken.mount=()=>{missingToken.root={hidden:true,innerHTML:'',dataset:{}}};
  assert.equal(await missingToken.start(),'error','lost token with known profile opens recovery instead of onboarding');
  assert.equal(mistakenRolePrompts,0);
  memory.set('duofit.auth.v1',JSON.stringify({refresh_token:'saved',user:{id:'u1'}}));
  const refreshTest=new DuoCoach({});refreshTest.session={refresh_token:'saved'};refreshTest.authRequest=async()=>{throw new Error('offline')};
  await assert.rejects(refreshTest.refresh(),/offline/,'network failure is surfaced');
  assert(refreshTest.session?.refresh_token,'network failure preserves the refresh token');
  refreshTest.saveSession({access_token:'access',refresh_token:'saved',expires_in:3600});
  refreshTest.authRequest=async()=>{throw new Error('refresh should not be called before expiry')};
  assert.equal(await refreshTest.refresh(),true,'new sessions retain their expiry and avoid unnecessary refresh');
  const retryAuth=new DuoCoach({});retryAuth.saveSession({access_token:'stale',refresh_token:'saved',expires_in:3600,user:{id:'u1'}});
  let authAttempts=0,authRefreshes=0;retryAuth.request=async()=>{authAttempts++;if(authAttempts===1){const e=new Error('unauthorized');e.status=401;throw e}return {ok:true}};
  retryAuth.authRequest=async()=>{authRefreshes++;return {access_token:'renewed',refresh_token:'renewed',expires_in:3600,user:{id:'u1'}}};
  assert.equal((await retryAuth.rpc('fl_private_pull')).ok,true,'unauthorized pull retries with a fresh token');
  assert.equal(authAttempts,2);assert.equal(authRefreshes,1);
  const oldSession={access_token:'old',refresh_token:'old-refresh',user:{id:'u1'}};
  const retryRecovery=new DuoCoach({});retryRecovery.session=oldSession;retryRecovery.hadSavedSession=true;retryRecovery.signInAnonymous=async()=>retryRecovery.saveSession({access_token:'new',refresh_token:'new-refresh',user:{id:'u2'}});retryRecovery.rpc=async()=>{throw new Error('invalid_recovery_code')};
  await assert.rejects(retryRecovery.recover('A'.repeat(32)),/invalid_recovery_code/);
  assert.equal(retryRecovery.session.access_token,'old','failed recovery keeps the prior saved session');
  await peerSafe.issueRecoveryCode();assert(/^[A-F0-9]{4}(-[A-F0-9]{4}){7}$/.test(peerSafe.recoveryCode),'recovery code shown in groups');assert(pushed.includes('fl_recovery_set'));
  let cleared=false;peerSafe.h.clearIdentity=()=>{cleared=true};peerSafe.request=async()=>({});peerSafe.session={access_token:'token',user:{id:'u1'}};
  await peerSafe.click({target:{closest:()=>({dataset:{coach:'signout'}})}});assert(peerSafe.member,'signout asks before clearing');
  await peerSafe.click({target:{closest:()=>({dataset:{coach:'signout-confirm'}})}});assert(cleared&&peerSafe.member===null,'signout hides private account');
  let recoverHash='';const recovering=new DuoCoach({setIdentity(){},setStore(){},render(){},getCheckin:()=>({}),family:()=>''});recovering.root={hidden:false,innerHTML:'',dataset:{}};recovering.authRequest=async()=>({access_token:'new-anon',refresh_token:'refresh',user:{id:'anon-2'}});recovering.rpc=async(name,args)=>{if(name==='fl_recover_role'){recoverHash=args.p_hash;return pulled.member}if(name==='fl_private_pull')return pulled;return null};
  await recovering.recover(peerSafe.recoveryCode);assert.equal(recoverHash.length,64);assert.equal(recovering.member.person,'hus');assert(recovering.recoveryCode,'new code issued after recovery');
  c.step=0;c.renderOnboard();assert.equal(c.root.dataset.person,'hus','husband onboarding selects blue theme');
  assert(c.weeklyCard().includes('本周身体状态')&&c.dailyCard().includes('每日状态'),'home cards show goal and today state');
  const aiBeforePair=new DuoCoach({family:()=>''});aiBeforePair.member={person:'hus',family:'abcdefgh'};aiBeforePair.provisional=true;aiBeforePair.session={access_token:'anon'};let sent=null,waitLimit=0,refreshCalls=0;aiBeforePair.refresh=async()=>{refreshCalls++;return true};aiBeforePair.request=async(_,body,__,timeout)=>{sent=body;waitLimit=timeout;return {summary:'已理解'}};await aiBeforePair.coachAI('interpret','想减脂',{step:0});assert.equal(sent.person,'hus','AI can receive role before pairing');assert.equal(waitLimit,60000,'client waits long enough for the server interpretation deadline');assert.equal(refreshCalls,1,'AI refreshes the login session before sending');await aiBeforePair.coachAI('plan','生成计划');assert.equal(waitLimit,90000,'plan request covers the server retry window');aiBeforePair.request=async()=>{const e=new Error('Function not found');e.status=404;throw e};await aiBeforePair.coachAI('interpret','想减脂',{step:0});assert(aiBeforePair.aiError.includes('尚未部署'),'missing AI function has actionable message');assert.equal(aiBeforePair.aiErrorContext,0,'AI error belongs to the step where it happened');aiBeforePair.request=async()=>{const e=new Error('ai_timeout');e.status=504;throw e};await aiBeforePair.coachAI('interpret','想减脂',{step:0});assert(aiBeforePair.aiError.includes('响应太慢'),'slow AI has a specific retry message');
  aiBeforePair.request=async()=>{const e=new Error('ai_invalid_output');e.status=502;throw e};assert.equal((await aiBeforePair.coachAI('interpret','想减脂',{step:0})).partial,true,'deployed older function format error uses client fallback');
  const choiceBefore=[...aiBeforePair.draft.goals];aiBeforePair.applySuggestions({goals:['更轻松']});assert.deepEqual([...aiBeforePair.draft.goals],choiceBefore,'unrecognized AI category does not erase selected goal');
  classSandbox.fetch=async()=>({ok:false,status:400,text:async()=>JSON.stringify({msg:'Anonymous sign-ins are disabled'})});await assert.rejects(new DuoCoach({}).authRequest('/auth/v1/signup',{}),/尚未开启免邮箱进入/,'disabled anonymous auth is translated');
  console.log('PASS coach health guard, daily alternatives, AI preview, weekly confirmation, private sync, anonymous entry, recovery, signout');
})().catch(e=>{console.error(e);process.exitCode=1});

assert.equal(app.refreshCalendarDay(),false,'same calendar day does not refresh');
const futureDate=new Date(Date.now()+864e5);
sandbox.Date=class extends Date {constructor(...args){super(...(args.length?args:[futureDate]));}};
assert.equal(app.refreshCalendarDay(),true,'calendar day updates independently of network sync');
assert(element('#dateLabel').textContent.includes((futureDate.getMonth()+1)+'月'+futureDate.getDate()+'日'),'header advances with the calendar');
sandbox.Date=Date;

// Same source priority and skipped-food semantics across meal surfaces.
app.setMe('hus');app.setCoach(coach);coach.profile.diet='';
coach.mealSwap=()=>'<em>个性餐食</em> + 蔬菜，保留全部份量和限制说明';
app.setStore({checkins:{['hus_'+date]:{person:'hus',date,meals:{breakfast:'plan'},food:{breakfast:{items:[{n:'保存的餐食',q:'1 份',k:777}],kcal:777}}}},measures:{}});
app.viewToday();let mealMarkup=element('#view').innerHTML;
assert(mealMarkup.includes('&lt;em&gt;个性餐食&lt;/em&gt;'),'custom plan is escaped');
assert(!mealMarkup.includes('class="foods"'),'a custom plan does not also display the default menu');
assert(mealMarkup.includes('777')&&mealMarkup.includes('保存的餐食'),'saved food and calories remain visible');
app.viewDiet();assert(!element('#view').innerHTML.includes('class="foods"'),'diet uses the same plan priority');
coach.profile.diet='不吃奶制品';coach.mealSwap=()=>'';app.viewToday();assert(element('#view').innerHTML.includes('餐食待确认')&&!element('#view').innerHTML.includes('class="foods"'),'restricted missing plan cannot fall back to default foods');
app.setStore({checkins:{['hus_'+date]:{person:'hus',date,meals:{breakfast:'skip'},food:{breakfast:{items:[{n:'保留的旧食物',q:'1 份'}],kcal:777}}}},measures:{}});
app.viewToday();assert(!element('#view').innerHTML.includes('777')&&!element('#view').innerHTML.includes('保留的旧食物'),'skipped Today meal hides stale food calories like history');
console.log('PASS shared meal plan priority, escaping, saved calories and skipped-food semantics');
