// Synthetic examples only: no auth, persistence, cloud calls or personal records.
let role='hus';
const icon=(n,small=false)=>`<svg class="ui-icon${small?' sm':''}" viewBox="0 0 24 24" aria-hidden="true"><use href="#ic-${n}"/></svg>`;
const meals=[['breakfast','早餐','7:00','330–545','燕麦 60g、无糖豆浆 300ml、水煮蛋 2 个','豆皮包 1 个、脱脂牛奶 200ml',280],['lunch','午餐','12:00','640–840','杂粮饭 150g、清蒸鸡胸 120g、西兰花 200g','清汤面 250g、蔬菜沙拉 100g',375],['snack','下午加餐','16:00','150–340','原味酸奶 150g、苹果 1 个','',null],['dinner','晚餐','20:00 后','585–785','清蒸鱼 150g、绿叶蔬菜 250g、米饭半碗','',null]];
const art=m=>`<span class="meal-art-stage"><img class="meal-art" src="../assets/meal-art/${m}${['breakfast','lunch'].includes(m)?'-detail-v1.webp?v=detail1':'-v1.webp?v=meal1'}" width="140" height="86" alt="" loading="lazy" decoding="async"></span>`;
const energy=v=>`<span class="meal-energy"><small>约</small><b>${v}</b><small>kcal</small></span>`;
function heading(title,kind){return `<div class="ds-section-heading ${role}"><div><h3>${title}</h3><time>10月9日 周五</time></div>${window.DuoFitMascots.render(kind,role,'../')}</div>`;}
function rowHead(m,plan=false){return `<div class="meal-heading">${plan?art(m[0]):`<span class="meal-symbol" aria-hidden="true">${icon(m[0])}</span>`}<div class="meal-title"><h4>${m[1]}</h4><time>${m[2]}</time></div>${plan?energy(m[3]):art(m[0])}</div>`;}
function actions(){return `<div class="ds-checkin ${role}" role="group" aria-label="示例餐次打卡">${['按计划','吃多了','没吃'].map((n,i)=>`<button type="button" aria-pressed="${i===0}"><span class="check-indicator" aria-hidden="true">${i===0?icon('check',true):''}</span>${n}</button>`).join('')}</div>`;}
function render(){
 document.body.className='ds-root me-'+role;
 document.querySelectorAll('#roleControl button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.role===role)));
 document.querySelector('#roleControl').className='ds-role-tabs '+role;
 const cols=[`<article class="pattern-column ${role}"><p class="pattern-name">今日 / 可编辑</p><section class="ds-scene ${role}">${heading('今天吃什么','today')}${meals.slice(0,2).map(m=>`<article class="card meal ${role}">${rowHead(m)}<div class="meal-body"><div class="meal-plan-range"><span>计划</span>${energy(m[3])}</div><div class="mplan-suggestion"><p>${m[4]}</p></div><div class="meal-actual"><div class="meal-actual-top"><span>实际记录</span>${energy(m[6])}<button class="meal-edit" type="button">修改${icon('chevron-right',true)}</button></div><p class="meal-food-text">${m[5]}</p></div>${actions()}</div></article>`).join('')}</section></article>`,
 `<article class="pattern-column ${role}"><p class="pattern-name">饮食 / 我的计划</p><section class="ds-scene ${role}">${heading('我的一天','diet')}<div class="card meal-plan-list ${role}">${meals.map(m=>`<article class="mplan">${rowHead(m,true)}<div class="mplan-suggestion"><p>${m[4]}</p></div></article>`).join('')}</div></section></article>`,
 `<article class="pattern-column ${role}"><p class="pattern-name">记录 / 本人或伴侣只读</p><section class="ds-scene ${role}">${heading('我们的记录','record')}${coupleExample()}<div class="history-day ${role}"><div class="ds-role-tabs" id="exampleRecords" role="group" aria-label="查看示例记录">${['hus','wife'].map(p=>`<button type="button" class="${p}" data-example-person="${p}" aria-pressed="${p===role}">${icon('person',true)}${p==='hus'?'老公':'老婆'}</button>`).join('')}</div><div class="history-view-label"><span id="recordCaption">正在查看${role==='hus'?'老公':'老婆'}的记录 · 只读</span></div><div class="diary-meals">${meals.map((m,i)=>`<article class="diary-meal" data-meal-status="${i<2?'plan':'empty'}"><div class="diary-meal-head"><span class="meal-symbol">${icon(m[0])}</span><div><h4>${m[1]}</h4><span class="meal-status ${i<2?'plan':'empty'}">${i<2?'按计划':'未打卡'}</span></div>${i<2?energy(m[6]):''}</div><p class="diary-food">${m[5]||'还没有留下这餐的记录'}</p></article>`).join('')}</div><div class="ds-activity-list"><div class="history-activity"><span>${icon('train',true)}训练</span><b>已完成</b></div><div class="history-activity"><span>${icon('desk',true)}起身活动</span><b>4 次</b></div></div></div></section></article>`];
 document.querySelector('#patterns').innerHTML=cols.join('');
 document.querySelector('#modulePatterns').innerHTML=moduleExamples();
 swatches();
}
// Examples use the same module shell/classes; counts below are explicitly synthetic.
function coupleExample(){return `<div class="habit-card"><div class="habit-heading"><div><h4>一起坚持的日子</h4><p>每一次记录，都是在照顾自己。</p></div></div><div class="habit-people">${['hus','wife'].map((p,i)=>`<div class="habit-person ${p}"><div class="habit-person-head"><img src="../assets/avatar-${p}.webp?v=media1" alt="" width="32" height="32"><b>${p==='hus'?'老公':'老婆'}</b></div><span class="habit-label">连续记录</span><div class="habit-number"><b>${5-i}</b><span>天</span></div><small>本周记录 ${5-i} 天</small></div>`).join('')}</div><p class="habit-note">示例数据。真实 App 先展示双人概览与日历，再查看个人详情。</p></div>`;}
function moduleExample(title,body,meta,symbol,art=''){return `<section class="ds-scene ds-module ${role}"><header class="ds-module-heading"><div><h3>${title}</h3><p>${meta}</p></div>${art?`<img class="ds-module-art" src="../assets/mood/${role}-${art}.webp?v=media1" width="88" height="88" alt="">`:`<span class="ds-module-mark">${icon(symbol)}</span>`}</header><div class="ds-module-body">${body}</div></section>`;}
function moduleExamples(){return moduleExample('工位起身',`<div class="counter"><div class="txt"><h4>起来动一动</h4><p>每坐 1 小时起身 2–3 分钟</p></div><div class="ctl"><button data-stand="-1" aria-label="示例减一次">−</button><b><span id="standExample">4</span><small>/6 次</small></b><button data-stand="1" aria-label="示例加一次">+</button></div></div>`,'给久坐的身体一个小休息','','workout')+moduleExample('饮食日志',`<div class="nutrition-summary"><div class="nutrition-top"><span>今日热量估算</span><span class="nutrition-count">3 / 4 餐已记录</span></div><div class="nutrition-value"><div><b>655</b><small>kcal</small></div></div><div class="nutrition-track"><span style="width:42%"></span></div><p class="nutrition-note">示例记录 · 实际食物按记录计算</p></div>`,'把每一餐，慢慢记下来','diet')+moduleExample('数据与趋势',`<div class="ds-stat"><span>最近记录 · 示例</span><p><b>76</b> kg</p></div><section class="ds-module-section"><h4>趋势</h4><p class="ds-module-note">输入、趋势和最近更新共用一张卡，实际图表按保存的数据绘制。</p></section><section class="ds-module-section"><h4>最近更新</h4><p class="ds-module-note">今天 · 76 kg</p></section>`,'记录、趋势与更新，都在这里','','weigh');}
function swatches(){const cs=getComputedStyle(document.body),names=[['页面','--bg'],['卡片','--surface'],['次表面','--sunk'],['主文字','--ink'],['角色强调',`--${role}`],['角色文字',`--${role}-ink`],['角色浅色',`--${role}-soft`],['辅助文字','--muted']];document.querySelector('#swatches').innerHTML=names.map(([n,t])=>`<div class="swatch"><div class="sample" style="background:var(${t})"></div><b>${n}</b><code>${t}</code><code>${cs.getPropertyValue(t).trim()}</code></div>`).join('');}
document.querySelector('#roleControl').addEventListener('click',e=>{const b=e.target.closest('[data-role]');if(b){role=b.dataset.role;render();}});
document.querySelector('#themeControl').addEventListener('change',e=>{if(e.target.value==='system')delete document.documentElement.dataset.theme;else document.documentElement.dataset.theme=e.target.value;swatches();});
matchMedia('(prefers-color-scheme:dark)').addEventListener('change',()=>swatches());
document.querySelector('#patterns').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.closest('.ds-checkin')){const group=b.closest('.ds-checkin');group.querySelectorAll('button').forEach(x=>{x.setAttribute('aria-pressed',String(x===b));x.querySelector('.check-indicator').innerHTML=x===b?icon('check',true):'';});}else if(b.dataset.examplePerson){const group=b.closest('.ds-role-tabs'),owner=b.dataset.examplePerson;group.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));group.closest('.history-day').className='history-day '+owner;document.querySelector('#recordCaption').textContent=`正在查看${owner==='hus'?'老公':'老婆'}的记录 · 只读`; }else if(b.classList.contains('meal-edit')){document.querySelector('#foodExample').focus();document.querySelector('#saveStatus').textContent='示例编辑区已打开，下方输入仅用于演示。';}});
document.querySelector('#saveExample').addEventListener('click',e=>{const b=e.currentTarget;b.disabled=true;b.setAttribute('aria-busy','true');b.textContent='保存中…';document.querySelector('#saveStatus').textContent='正在演示保存状态…';setTimeout(()=>{b.disabled=false;b.removeAttribute('aria-busy');b.textContent='保存示例';const s=document.querySelector('#saveStatus');s.dataset.tone='success';s.textContent='演示完成，未写入任何个人记录。';},650);});
render();

document.querySelector('#modulePatterns').addEventListener('click',e=>{const b=e.target.closest('[data-stand]');if(b){const n=document.querySelector('#standExample');n.textContent=String(Math.max(0,Number(n.textContent)+Number(b.dataset.stand)));}});
